services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env.dev
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=guscorp"
    ports:
      - 5432:5432
  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  celery_worker:
    build: .
    command: celery -A django_project worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    env_file:
      - .env.dev

volumes:
  postgres_data:
  redis_data:
